'use strict';
(function(){
    //This file was generated by the LTK DCI DB Creator Web UI Tab
    var nav, tab, section, group, param;
    
    nav = navbar.create('Seed User Interface','nav-app',undefined,'#/seed_user_interface');
    tab = nav.create('Overview','tab-overview','px-icons:overview','#/seed_user_interface/overview');
    tab = nav.create('Current','tab-current','px-icons:energy','#/seed_user_interface/current');
    tab = nav.create('I/O','tab-io','px-icons:in-out','#/seed_user_interface/io');
    tab = nav.create('Timeline','tab-timeline','px-icons:timeline','#/seed_user_interface/timeline');
    nav = navbar.create('Settings','nav-settings','px-icons:settings','#/settings');
    tab = nav.create('General','tab-app_settings','px-icons:general','#/settings/app_settings');
    tab = nav.create('Network','tab-network','px-icons:network','#/settings/network');
    tab = nav.create('User Settings','tab-user_settings','px-icons:user','#/settings/user_settings');
    tab = nav.create('Firmware','tab-firmware','px-icons:key','#/settings/firmware');
    tab = nav.create('Logs','tab-logs','px-icons:details','#/settings/logs');
    
})();
