/**
 *****************************************************************************************
 * @file
 * @brief This file Shell_commands.cpp contains implementation for the test suite.
 *
 * @warning This file is automatically generated by a Python script.
 * Do not manually edit this file - any changes will be overwritten!!!
 *
 * @author CodeGenerator.py
 * @date Generated:  2016-12-23 12:55:25.372000
 * @copyright 2015 Eaton Corporation. All Rights Reserved.
 *****************************************************************************************
 */

#include "Shell_Includes.h"

namespace Shell
{

/*
 *****************************************************************************************
 * See header file for table definition.
 *****************************************************************************************
 */
Shell::Test_Base* g_shell_cmd_table_instance[] =
{
	&g_I2C_Simple_Class_Async_NO_DMA_Instance,
	&g_I2C_Simple_Class_Sync_NO_DMA_Instance,
	&g_I2C_Simple_Class_Async_DMA_Instance,
	&g_I2C_Queued_Class_Instance,
	&g_My_FIFO_TEST_ID_1_Instance,
	&g_My_FIFO_TEST_ID_2_Instance,
	&g_My_FIFO_TEST_ID_3_Instance,
	&g_My_FIFO_TEST_ID_4_Instance,
	&g_My_FIFO_TEST_ID_5_Instance,
	&g_My_FIFO_TEST_ID_6_Instance,
	&g_Voltage_Monitor_TEST_ID_1_Instance,
	&g_Voltage_Monitor_TEST_ID_2_Instance,
	&g_Voltage_Monitor_TEST_ID_3_Instance,
	&g_Voltage_Monitor_TEST_ID_4_Instance,
	&g_Mem_Check_TEST_ID_1_Instance,
	&g_Com_Dog_TEST_ID_1_Instance,
	&g_Com_Dog_TEST_ID_2_Instance,
	&g_Com_Dog_TEST_ID_3_Instance,
	&g_Bi_Color_LED_TEST_ID_1_Instance,
	&g_Bi_Color_LED_TEST_ID_2_Instance,
	&g_Bi_Color_LED_TEST_ID_3_Instance,
	&g_Bi_Color_LED_TEST_ID_4_Instance,
	&g_Bi_Color_LED_TEST_ID_5_Instance,
	&g_Bi_Color_LED_TEST_ID_6_Instance,
	&g_Bi_Color_LED_TEST_ID_7_Instance,
	&g_Lib_Bit_List_TEST_ID_1_Instance,
	&g_Lib_Bit_List_TEST_ID_2_Instance,
	&g_Lib_Bit_List_TEST_ID_3_Instance,
	&g_Lib_Bit_List_TEST_ID_4_Instance,
	&g_Lib_Bit_List_TEST_ID_5_Instance,
	&g_Lib_Bit_List_TEST_ID_6_Instance,
	&g_Lib_Bit_List_TEST_ID_7_Instance,
	&g_Lib_Bit_List_TEST_ID_8_Instance,
	&g_Lib_Bit_List_TEST_ID_9_Instance,
	&g_Lib_Bit_List_TEST_ID_10_Instance,
	&g_Lib_Bit_List_TEST_ID_11_Instance,
	&g_Lib_Bit_List_TEST_ID_12_Instance,
	&g_Lib_Bit_List_TEST_ID_13_Instance,
	&g_BF_Shell_TEST_ID_1_Instance,
	&g_BF_Shell_TEST_ID_3_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_1_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_2_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_3_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_4_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_5_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_6_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_7_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_8_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_9_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_10_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_11_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_12_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_13_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_14_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_15_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_16_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_17_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_18_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_19_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_20_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_21_Instance,
	&g_TimeConversion_TimeUtil_TEST_ID_22_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_1_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_2_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_3_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_4_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_5_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_6_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_7_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_8_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_9_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_10_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_11_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_12_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_13_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_14_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_15_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_16_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_17_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_18_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_19_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_20_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_21_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_22_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_23_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_24_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_25_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_26_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_27_Instance,
	&g_TimeConversion_DateUtil_TEST_ID_28_Instance,
	&g_TimeConversion_POSIXTimeUtil_TEST_ID_1_Instance,
	&g_TimeConversion_POSIXTimeUtil_TEST_ID_2_Instance,
	&g_TimeConversion_TimeZoneDST_TEST_ID_1_Instance,
	&g_TimeConversion_TimeZoneDST_TEST_ID_2_Instance,
	&g_TimeConversion_TimeZoneDST_TEST_ID_3_Instance,
	&g_TimeConversion_TimeZoneDST_TEST_ID_4_Instance,
	&g_TimeConversion_TimeZoneDST_TEST_ID_5_Instance,
	&g_BF_Modbus_TEST_1_Instance,
	&g_Ram_NV_TEST_ID_1_Instance,
	&g_Ram_NV_TEST_ID_2_Instance,
	&g_Ram_NV_TEST_ID_3_Instance,
};

}	/* end namespace Shell */

