/**
 *	@file    app.h
 *
 *
 *	Header for MatrixSSL example sockets client and server applications.
 */
/*
 *	Copyright (c) 2013-2016 INSIDE Secure Corporation
 *	All Rights Reserved
 *
 *	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF INSIDE.
 *
 *	Please do not edit this file without first consulting INSIDE support.
 *	Unauthorized changes to this file are not supported by INSIDE.
 *
 *	The copyright notice above does not evidence any actual or intended
 *	publication of such source code.
 *
 *	This Module contains Proprietary Information of INSIDE and should be
 *	treated as Confidential.
 *
 *	The information in this file is provided for the exclusive use of the
 *	licensees of INSIDE. Such users have the right to use, modify,
 *	and incorporate this code into products for purposes authorized by the
 *	license agreement provided they include this notice and the associated
 *	copyright notice with any such product.
 *
 *	The information in this file is provided "AS IS" without warranty.
 */
/******************************************************************************/

#ifndef _h_MATRIXSSLAPP
#define _h_MATRIXSSLAPP

#ifdef __cplusplus
extern "C" {
#endif

#ifdef ESP32_SETUP
#include <sys/errno.h>
#endif
/*
     Platform independent socket defines for convenience
 */
#ifndef INVALID_SOCKET
 #define INVALID_SOCKET ( -1 )
typedef int32_t SOCKET;
#endif


#ifdef WIN32
 #define SOCKET_ERRNO   WSAGetLastError()
#elif ESP32_SETUP
 #define SOCKET_ERRNO   errno	// Not using BF lwip errno.h for ESP32 (TBD)
#else
 #define SOCKET_ERRNO   lwip_errno
#endif


#ifdef __cplusplus
}
#endif

#endif	/* _h_MATRIXSSLAPP */

/******************************************************************************/
