/**
*****************************************************************************************
*   @file
*
*   @brief Autogenerated NV Memory map address file.
*
*   @details
*
*   @version
*   C++ Style Guide Version 1.0
*
*   @copyright 2022 Eaton Corporation. All Rights Reserved.
*
*****************************************************************************************
*/
#ifndef NV_DEFAULT_H
  #define NV_DEFAULT_H


//***************************************************************************
// Typedef
//***************************************************************************

typedef struct
{
    uint8_t const* data;
    uint32_t address;
    uint32_t length;
} NV_DEFAULT_LIST_ITEM_TD;


//***************************************************************************
// Chip Range and Extern
//***************************************************************************

#define NV_DEFAULT_LIST_ITEM_COUNT                0


#endif
