@echo off
set help_required=0
::input_web_bin_name this variable holds the name of the web binary generated by buildToUpgrade.bat 
set input_web_bin_name=www
:: output_web_bin_name this variable holds the name of the resultant web binary file generated after addition of header and signature to bin
set output_web_bin_name=web
:: this is the name of the xml file that serves as an argument to ltk_header_gen.exe using which it can create the header for the binary file
set web_header_input_xml=web_header_linker.xml
IF "%1" == "-help" (
GOTO HELP
)
IF "%1" == "--help" (
GOTO HELP
)
IF "%1%" == "-h" (
GOTO HELP
)
IF "%1%" == "--h" (
GOTO HELP
)

:SET_ENVIRONMENT
cd..
cd..
cd Code\Ethernet\Web\WebUI\LTK_Seed
IF NOT "%help_required%" == "1" (
::tk_header_gen.exe -input_file %input_web_bin_name%.bin -output_file %output_web_bin_name%.bin -input_xml %web_header_input_xml% -header_size 64 -header_default_value 0
:: if -header_size is not specified then default value of header size is considered
:: if -header_default_value is not specified then default value 0 is considered
ltk_header_gen.exe -input_file %input_web_bin_name%.bin -output_file %output_web_bin_name%.bin -input_xml %web_header_input_xml%
)
cd..
cd..
cd..
cd..
cd..
cd Tools\FW_Upgrade
set par1=%1
set par2=%2
set par3=%3
set par4=%4
set par5=%5
set par6_HexbaseAddr=%6
set PATH=%~dp0
set CURDIR=%CD%
set prj_path=..\..\..\
set RSK=RSK_Dev_4096.key
set FVK=FVK_Dev_2048.pub
set FSK=FSK_Dev_2048.key
set FVK_VERSION=1.1.1.1
set Web_Fw_HexBaseAddr=0x08080000
set App_fw_HexBaseAddr=0x08010000
set K6x_Web_Fw_HexBaseAddr=0x00100000
set K6x_App_fw_HexBaseAddr=0x00015000

IF NOT "%CURDIR%\" == "%PATH%" (
set prj_path=.\
)

set bin_path_207=%prj_path%Build_Output\STM32F207_With_UberLoader_Release\Exe\
set bin_path_407=%prj_path%Build_Output\STM32F407_With_UberLoader_Release\Exe\
set bin_path_437=%prj_path%Build_Output\STM32F437_With_UberLoader_Release\Exe\
set bin_path_765=%prj_path%Build_Output\STM32F765_With_UberLoader_Release\Exe\
set bin_path_767=%prj_path%Build_Output\STM32F767_With_UberLoader_Release\Exe\
set bin_path_427=%prj_path%Build_Output\STM32F427_With_UberLoader_Release\Exe\
set bin_path_K6x=%prj_path%Build_Output\K66FN2M0_Release\Exe\
set web_path=%prj_path%Babelfish\Code\Ethernet\Web\WebUI\LTK_Seed\
set batch_path=%prj_path%Babelfish\Tools\FW_Upgrade\
IF "%help_required%" == "1" (
GOTO CONTINUE_HELP
)

IF %2.==. GOTO Default
IF %3.==. GOTO No1
IF %4.==. GOTO No1
IF %5.==. GOTO No1
IF %6.==. GOTO No1

pk_sign %par1% %par2%
fvk_info -fvksig %par2% %par4% %par5%
set word=
set match=
call set par5=%%par5:.bin=%word%%%
call set par2=%%par2:.pub=%word%%%
pk_sign %par3% %par5%_payload.bin
fvk_info -fwsig  %par5%_payload.bin
bin2srec\srec_cat.exe %par5%_Upload_Pack.bin -binary -offset %par6_HexbaseAddr% -o %par5%_Upload_Pack.hex -intel --line-length=44
GOTO End1

:HELP
  ECHO ---------------------------------COMMAND FORMAT---------------------------------------
  ECHO fw_upgrade.(cmd/exe) RSK_File_Name.key FVK_File_Name.pub FSK_File_Name.key FVK_Version Bin_File_name.bin Output_Hex_Base_Address
  ECHO Where,
  ECHO FVK_Version             - The FVK version value should be in below Range and Format-
  ECHO                           {0.0.0.0} to {255.255.255.255}
  ECHO Output_Hex_Base_Address - Base address of output HEX file to be generated
  ECHO --------------------------------------------------------------------------------------
  ECHO fw_upgrade utility can also be executed without passing any parameter, In this case It will take below default values -
  set help_required=1
  GOTO SET_ENVIRONMENT
  :CONTINUE_HELP
  ECHO RSK_File_Name.key       - %batch_path%%RSK%
  ECHO FVK_File_Name.pub       - %batch_path%%FVK%
  ECHO FSK_File_Name.key       - %batch_path%%FSK%
  ECHO FVK_Version             - %FVK_VERSION%
  ECHO Bin_File_name(path)     - 1. %web_path%
  ECHO                         - 2. %bin_path_207%
  ECHO                         - 3. %bin_path_407%
  ECHO                         - 4. %bin_path_437%
  ECHO                         - 5. %bin_path_765%
  ECHO                         - 6. %bin_path_767%
  ECHO                         - 7. %bin_path_427%
  ECHO                         - 8. %bin_path_K6x%
  ECHO Output_Hex_Base_Address - 1. %Web_Fw_HexBaseAddr% (Web Firmware)
  ECHO                         - 2. %App_Fw_HexBaseAddr% (App Firmware)
  ECHO                         - 3. %K6x_Web_Fw_HexBaseAddr% ( K6x Web Firmware)
  ECHO                         - 4. %K6x_App_fw_HexBaseAddr% (K6x App Firmware) 
  ECHO --------------------------------------------------------------------------------------
GOTO End1

:Default
  ECHO %PATH%
  ECHO %CURDIR%
  ECHO %prj_path%
  ECHO App_Fw_Hex_Base_Address = %App_fw_HexBaseAddr%
  ECHO Web_Fw_Hex_Base_Address = %Web_Fw_HexBaseAddr%
  ECHO ---------------------------------------------------------------------------------------------------
  ECHO FORMAT of fw_upgrade.bat 
  ECHO fw_upgrade.bat RSK_File_Name.key FVK_File_Name.pub  FSK_File_Name.key FVK_Version Bin_file_name.bin Output_Hex_Base_Address
  ECHO Taking Default Paths for Upload Pack generation 
  ECHO ----------------------------------------------------------------------------------------------------

  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %web_path%%output_web_bin_name%.bin
  pk_sign %batch_path%%FSK% %web_path%%output_web_bin_name%_payload.bin
  fvk_info -fwsig %web_path%%output_web_bin_name%_payload.bin
  bin2srec\srec_cat.exe %web_path%%output_web_bin_name%_Upload_Pack.bin -binary -offset %Web_Fw_HexBaseAddr% -o %web_path%%output_web_bin_name%_Upload_Pack.hex -intel --line-length=44
  ECHO Web Firmware Upload Pack Generation Completed

  hex2bin -b %bin_path_407%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_407%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_407%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_407%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_407%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_407%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 407 Sample application Upload Pack Generation Completed


  hex2bin -b %bin_path_437%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_437%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_437%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_437%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_437%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_437%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 437 Sample application Upload Pack Generation Completed
  
  hex2bin -b %bin_path_207%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_207%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_207%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_207%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_207%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_207%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 207 Sample application Upload Pack Generation Completed
  
  hex2bin -b %bin_path_765%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_765%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_765%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_765%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_765%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_765%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 765 Sample application Upload Pack Generation Completed
  
  hex2bin -b %bin_path_767%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_767%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_767%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_767%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_767%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_767%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 767 Sample application Upload Pack Generation Completed
  
  hex2bin -b %bin_path_427%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_427%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_427%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_427%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_427%RTK_Example_Upload_Pack.bin -binary -offset %App_fw_HexBaseAddr% -o %bin_path_427%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO 427 Sample application Upload Pack Generation Completed
  
  hex2bin -b %bin_path_K6x%RTK_Example.hex	
  pk_sign %batch_path%%RSK% %batch_path%%FVK%
  fvk_info -fvksig %batch_path%%FVK% %FVK_VERSION% %bin_path_K6x%RTK_Example.bin
  pk_sign %batch_path%%FSK% %bin_path_K6x%RTK_Example_payload.bin
  fvk_info -fwsig %bin_path_K6x%RTK_Example_payload.bin
  bin2srec\srec_cat.exe %bin_path_K6x%RTK_Example_Upload_Pack.bin -binary -offset %K6x_App_fw_HexBaseAddr% -o %bin_path_K6x%RTK_Example_Upload_Pack.hex -intel --line-length=44
  ECHO K6x Sample application Upload Pack Generation Completed
  
GOTO End1

:No1
 
:End1