# This is a esp idf workflow to build ESP32 based project

name: Build and Artifact the ESP-IDF Project

# Controls when the action will run. 
on:
  # Triggers the workflow on tag create like v1.0, v2.0.0 and so on
  push:
    tags:
     - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    #  - name: Install ESP-IDF and Build project
    #    uses: rmshub/esp-idf-action@v5
    #    with: 
    #        esp_idf_version: v4.4.4
    #        esp_idf_target: esp32
#
    #  - name: Archive build output artifacts
    #    uses: actions/upload-artifact@v3
    #    with:
    #      name: build
    #      path: |
    #        build/*

    # we will download Esp idf and use it to build the project,
    # Alternatively we should also be able to use the custom IDF to build the project.
    steps: 
      - name: Install  preerequisites for ESP-IDF
        run: |
            sudo apt-get install git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        
      - name: Get ESP-IDF
        run: |
            mkdir -p ~/esp
            cd ~/esp
            git clone -b v4.0 --recursive https://github.com/espressif/esp-idf.git

      - name: Setting up the environment
        run: |
            cd ~/esp/esp-idf
            ./install.sh esp32
            . $HOME/esp/esp-idf/export.sh
            echo "alias get_idf='. $HOME/esp/esp-idf/export.sh'" >> "$HOME/.bashrc"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: cd into code
        run: |
            echo $GITHUB_WORKSPACE
            cd $GITHUB_WORKSPACE
            #git submodule update --init --recursive
      - name: see directories
        run: | 
            pwd
      - name: see files
        run: |
            ls
      - name: Build project
        run: |
            source ~/esp/esp-idf/export.sh
            idf.py build

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*


# Trying Release

