name: Build
run-name: ${{ github.workflow }}_${{ github.ref_name }}_${{ github.run_number }}.${{ github.run_attempt }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read


on:
  workflow_dispatch:
    inputs:
      create_tag_and_release:
        description: "Set this to true to create tag and release"
        default: 'false'
        required: false
        type: string
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # workaround when working in container, https://github.com/actions/runner/issues/2058
      # use ${{ env.WORKSPACE }} in succeeding steps to access github workspace path
      - name: Set Github workspace environment variable
        run: |
          if [[ -n "${{ job.container.id }}" ]];then
            echo "WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          else
            echo "WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
          #submodules: recursive
          #token:$ {{ secrets.MY_SECRET }}

      - name: Install toolchain
        run: |
          cd ${{github.workspace}}/esp32_common/esp-idf
          echo #%cd%
          install.bat >install_log.txt 2>&1
          ${{github.workspace}}\esp32_common\esp-idf\export.bat
          
          echo "********************************************"
        shell: cmd

      
         
      
      - name: Coverity Scan
        uses: synopsys-sig/synopsys-action@v1.11.0
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
          coverity_policy_view: 'Outstanding Issues'
          coverity_build_command: create_build.bat
          coverity_clean_command: clean_project.bat
          coverity_local: true
          exclude: 
            ${{github.workspace}}/Babelfish/
            ${{github.workspace}}/esp32_common

          run: |
            echo "Now setting the compiler to xtesna elf 32 gcc."
            cov-configure  --template --compiler xtensa-esp32-elf-gcc

      # this should be ideally done by coverity.
      - name: build
        run: |
            cd ${{github.workspace}}
            echo %cd%
            echo "********************************************"
            ${{github.workspace}}\esp32_common\esp-idf\export.bat && idf.py build
        shell: cmd